[package]
name = "sql_gen"
version.workspace = true
authors.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
description = "SQL generator with type-state capabilities, runtime policy, and invisible tracing"

[lib]
path = "src/lib.rs"

[features]
serde = ["dep:serde"]

[dependencies]
proptest = "1.9"
rand = { workspace = true }
sql_gen_macros = { path = "../sql_gen_macros" }
strum = { workspace = true }
anarchist-readable-name-generator-lib = "0.2.0"
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1.9"

[lints]
workspace = true
