[package]
name = "turso-ruby"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
name = "turso"
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.8.2", features = ["rb-sys"] }
turso_sdk_kit = { path = "../../../../sdk-kit" }
turso_core = { path = "../../../../core" }

[build-dependencies]
rb-sys-env = "0.2.2"
