[package]
name = "turso-ruby"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "turso"
crate-type = ["cdylib"]

[features]
extension-module = ["dep:magnus"]

[dependencies]
magnus = { version = "0.8.2", features = ["rb-sys"], optional = true }
turso_sdk_kit = { workspace = true }
turso_core = { workspace = true }
once_cell = "1.21.3"
tracing.workspace = true

[build-dependencies]
rb-sys-env = "0.2.2"
