[project]
name = "mobibench-plot"
version = "0.1.0"
description = "Mobibench SQLite vs Turso benchmark plotting"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "pandas>=2.3.2",
    "scienceplots>=2.1.1",
]
