[package]
name = "sqlsmith-rs-executor"
version = "0.1.0"
edition = "2021"

[lib]
path = "engines/mod.rs"

[[bin]]
name = "executor"
path = "main.rs"

[dependencies]
anyhow.workspace = true
fern = "0.7.1"
humantime = "2.2.0"
turso.workspace = true
log = "0.4.27"
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
chrono.workspace = true
reqwest = { version = "0.11", features = ["json","blocking"] }
sqlsmith-rs-common = { path = "../common" }
sqlsmith-rs-drivers = { path = "../drivers" }
futures.workspace = true
