[package]
name = "encryption-throughput"
version = "0.1.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "encryption-throughput"
path = "src/main.rs"

[dependencies]
turso = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, default-features = true, features = ["full"] }
futures = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
hex = { workspace = true }